# Generated by Django 4.0.1 on 2022-01-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
