# Generated by Django 4.0.1 on 2022-01-30 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_alter_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.ForeignKey(default='IT/Software Development', on_delete=django.db.models.deletion.CASCADE, to='job.category'),
        ),
    ]
