# Generated by Django 4.0.1 on 2022-02-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_apply_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
